spring:
  profiles:
    active: dev

---
spring:
  profiles:
    - dev
  application:
    name: user-service
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration