spring:
  profiles:
    active: dev
  application:
    name: user-service

server:
  port: 0

---
spring:
  config:
    activate:
      on-profile:
        - dev
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        generate_statistics: false
        format_sql: true
  boot:
    admin:
      client:
        url: http://localhost:9090
  sleuth:
    integration:
      enabled: true
    sampler:
      probability: 1
  zipkin:
    base-url: http://localhost:9411/

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    appname: user-service

---
spring:
  config:
    activate:
      on-profile:
        - test
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        generate_statistics: true
        format_sql: true
        connection:
          isolation: 2
        cache:
          use_second_level_cache: true
          region:
            factory_class: org.hibernate.cache.ehcache.internal.EhcacheRegionFactory
      javax:
        persistent:
          sharedCache:
            mode: ENABLE_SELECTIVE
  boot:
    admin:
      client:
        enabled: false
logging:
  level:
    org:
      hibernate:
        stat: debug
        type: trace
    net:
      sf:
        ehcache: debug
eureka:
  client:
    enabled: false
