spring:
  profiles:
    active: dev

---
spring:
  profiles:
    - dev
  application:
    name: user-service
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  h2:
    console:
      enabled: true

  jpa:
    show-sql: true
    properties:
      hibernate:
        generate_statistics: false
        format_sql: true