spring:
  profiles:
    active: dev
  boot:
    admin:
      client:
        url: http://localhost:9090

server:
  port: 8082

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
---
spring:
  config:
    activate:
      on-profile:
        - dev
  application:
    name: user-service
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
  h2:
    console:
      enabled: true

  jpa:
    show-sql: true
    properties:
      hibernate:
        generate_statistics: false
        format_sql: true

---
spring:
  config:
    activate:
      on-profile:
        - test
  application:
    name: user-service
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
  h2:
    console:
      enabled: true

  jpa:
    show-sql: true
    properties:
      hibernate:
        generate_statistics: true
        format_sql: true
        connection:
          isolation: 2
        cache:
          use_second_level_cache: true
          region:
            factory_class: org.hibernate.cache.ehcache.internal.EhcacheRegionFactory
      javax:
        persistent:
          sharedCache:
            mode: ENABLE_SELECTIVE
logging:
  level:
    org:
      hibernate:
        stat: debug
        type: trace
    net:
      sf:
        ehcache: debug