INSERT INTO USER_ROLE (ID, ROLE_NAME)
VALUES (1, 'ADMIN');
INSERT INTO USER_ROLE (ID, ROLE_NAME)
VALUES (2, 'USER');

INSERT INTO USER_DETAILS (ID, COUNTRY, EMAIL, FIRST_NAME, LAST_NAME, LOCALITY, PHONE_NUMBER, STREET, STREET_NUMBER,
                          ZIP_CODE)
VALUES (1, 'INDIA', 'user1@test.com', 'user1', 'one', 'test_local', '12345', 'test street', '123', '123456');
INSERT INTO USER_DETAILS (ID, COUNTRY, EMAIL, FIRST_NAME, LAST_NAME, LOCALITY, PHONE_NUMBER, STREET, STREET_NUMBER,
                          ZIP_CODE)
VALUES (2, 'INDIA', 'user2@test.com', 'user2', 'two', 'test_local', '12345', 'test street', '123', '123456');
INSERT INTO USER_DETAILS (ID, COUNTRY, EMAIL, FIRST_NAME, LAST_NAME, LOCALITY, PHONE_NUMBER, STREET, STREET_NUMBER,
                          ZIP_CODE)
VALUES (3, 'INDIA', 'user3@test.com', 'user3', 'three', 'test_local', '12345', 'test street', '123', '123456');

INSERT INTO USERS (ID, USER_NAME, PASSWORD, ACTIVE, ROLE_ID, USER_DETAILS_ID)
VALUES (1, 'user1', 'test1', 1, 1, 1);

INSERT INTO USERS (ID, USER_NAME, PASSWORD, ACTIVE, ROLE_ID, USER_DETAILS_ID)
VALUES (2, 'user2', 'test2', 1, 2, 2);

INSERT INTO USERS (ID, USER_NAME, PASSWORD, ACTIVE, ROLE_ID, USER_DETAILS_ID)
VALUES (3, 'user3', 'test3', 1, 2, 3);