name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: docker login
      uses: docker/login-action@v1
      with:
        username: ${{secrets.DOCKER_USER}}
        password: ${{secrets.DOCKER_PASSWORD}}
        logout: true

    - name: Build and Push the Docker image
      uses: docker/build-push-action@v2
      with:
        push: true
        context: ./
        file: ./Dockerfile
        tags: ${{ secrets.DOCKER_USER }}/${{ github.event.repository.name }}:latest

    - name: Image Digest
      run: echo ${{steps.docker_build.outputs.digest}}
